### ISSUE TITLE
ObjectController is instanciated twice

### ISSUE THREAD

**Issue by JordanP** [scality/ScalitySproxydSwift#113]
OpenStack Swift instantiates a WSGI application (could be the proxy-server, object server) twice, the first time to give the app a chance to change dynamically the WSGI pipeline, and then the pipeline is created.

Corresponding code is here : https://github.com/openstack/swift/blob/c77c79b2c9b9ca7790c29577341cf36c5e9012cf/swift/common/wsgi.py#L376

 A side effect is that an instance of the app is constructed twice.

This is an issue with our ObjectController which instantiates an SproxydClient that spawns a couple of healthcheck threads: we have twice the number of expected healthcheck threads.

Changing our setup() method to remove its side effect is not simple because we need the SproxydClient to be instantiated early to give time to the Accrual Failure detector to collect data.

**Comment by NicolasT** [comment]
@JordanP Disagree about the issue with the solution (of moving side-effects out of `setup()`): the `SproxydClient` code assumes nodes are available at startup, and will only remove them from the `alive` set when detected to be down, see https://github.com/scality/scality-sproxyd-client/blob/a84285a16327ee1cad04c2b05a343e936bc2f2e9/scality_sproxyd_client/sproxyd_client.py#L100

**Comment by NicolasT** [comment]
This should be handled in the `sp-support` branch (#86) through https://github.com/scality/ScalitySproxydSwift/pull/86/files#diff-62d652ba1e9735a2182159bbcbea59dfL63

**Comment by JordanP** [comment]
Fixed by #86 

ObjectController is still instantiated twice but the constructor has no side effect anymore, ie it doesn't spawn (green-thread
