### ISSUE TITLE
Add test for Range lookups

### ISSUE THREAD

**Issue by NicolasT** [scality/ScalitySproxydSwift#121]
Write tests to validate `Range` requests (including all possible combinations of defined or undefined boundaries) are handled correctly, all the way from frontend/proxy to the HTTP request going to sproxyd, to ensure issues similar to those encountered in https://github.com/scality/scality-glance-store/pull/15 are handled correctly.

**Comment by NicolasT** [comment]
@sbjorn Could you open a PR once you got something close-to-ready so we can launch a review?

**Comment by sbjorn** [comment]
This issue is handled by PR #129.

**Comment by NicolasT** [comment]
Closed through #129
