### ISSUE TITLE
Swift Icehouse functional tests on CentOS6 broken

### ISSUE THREAD

**Issue by NicolasT** [scality/ScalitySproxydSwift#125]
Somehow the Icehouse functional tests on CentOS6 broke. They used to run on May 12th (https://37.187.159.67:5443/job/swift-functional-tests/136/), but no longer work: it appears the Swift services can't be started.

It'd be useful to get them running again.

**Comment by JordanP** [comment]
This will be fixed by #130 (not ready for review yet).

**Comment by JordanP** [comment]
Fixed by #130
