### ISSUE TITLE
Minimize the number of open stack services that are run in the swift functional test job

### ISSUE THREAD

**Issue by cazino** [scality/ScalitySproxydSwift#131]
Since https://github.com/scality/ScalitySproxydSwift/pull/126, we run a lot of services in the swift functional test job. This increased a lot the devstack installation time.
Tempest installation through devstack requires some services like nova to be there. Which services are needed and why they are needed is pretty much undocumented, that's why we chose to enable almost every services. We should now find out exactly which services are needed and run only those ones.

**Comment by JordanP** [comment]
Resolved in #161
