### ISSUE TITLE
Add 'kilo' to 'tox' and 'functional-test' targets

### ISSUE THREAD

**Issue by NicolasT** [scality/ScalitySproxydSwift#134]
Swift 'head' started diverging from Kilo, so we should make sure we keep testing all supported versions.

**Comment by cazino** [comment]
I assume we should also keep a 'master' target ?

**Comment by NicolasT** [comment]
Indeed!

**Comment by cazino** [comment]
Done : https://37.187.159.67:5443/job/swift-functional-tests/

**Comment by JordanP** [comment]
We should not run stable/kilo on centos 6 because centos 6 comes with an old version of bash which devstack doesn't support.

**Comment by cazino** [comment]
I update the combination filter : centos6 + master an centos6 + kilo are excluded of a run.

**Comment by NicolasT** [comment]
When #136 is in, the `swift-tox` job can be extended as well.

**Comment by NicolasT** [comment]
`swift-tox` has been updated.
