### ISSUE TITLE
Get CentOS6 functional tests to succeed

### ISSUE THREAD

**Issue by NicolasT** [scality/ScalitySproxydSwift#137]
There's a third-party repository containing backported Apache packages (2.4), which when used should get the Swift functional test jobs to succeed on CentOS6/Python2.6.

https://repos.fedorapeople.org/repos/jkaluza/httpd24/epel-httpd24.repo

It'd be useful to spend some time on this.

**Comment by JordanP** [comment]
PR #164 documented that Centos 6 is supported but not tested automatically in our CI.
