### ISSUE TITLE
Missing resp.read() into the HEAD request

### ISSUE THREAD

**Issue by patrickdos** [scality/ScalitySproxydSwift#3]

**Comment by JordanP** [comment]
Patrick, could you elaborate on this one. Is it still relevant now ?

Thanks !

**Comment by NicolasT** [comment]
The only `HEAD` request is performed by `SproxydClient.get_meta`, which uses `_do_http`, which always drains the response upon success (unless a generator is returned by a handler), or fails after which a connection won't be reused.
