### ISSUE TITLE
Use eventlet.Timeout in DiskFileWriter

### ISSUE THREAD

**Issue by JordanP** [scality/ScalitySproxydSwift#32]
Currently, in the `DiskFileWriter` class, we are not wrapping any `conn.send()` call with an eventlet.Timeout() context manager. This may be an issue.

**Comment by NicolasT** [comment]
How long can a `send` of a single chunk take? If there's a timeout, it should be rather high, IMHO...

**Comment by JordanP** [comment]
What if the server/sproxyd dies horribly during the sending of a single chunk ?

**Comment by NicolasT** [comment]
Then the TCP connection is supposed to time-out after some time :wink:
I agree using a timeout could be a good thing, but it should be large enough, or (maybe even better) depend on the size of the chunk (say we define we want a throughput of at least 1KiB/s, we can select a timeout period according to the chunk size).

**Comment by JordanP** [comment]
>Then the TCP connection is supposed to time-out after some time
That could take dozens of seconds, right ?

I'll test what happens when the sproxyd dies during the `swift post` of a huge file. I just don't want the swift client to hang for dozens of seconds.
