### ISSUE TITLE
`put_meta()` and `del_object()` don't return anything

### ISSUE THREAD

**Issue by JordanP** [scality/ScalitySproxydSwift#33]
In the `SproxydFileSystem` class, the `put_meta()` and `del_object()` methods don't return anything. If we don't expect any response from Sproxyd, could we avoid calling `response.read()` ?

**Comment by NicolasT** [comment]
I'm not 100% certain, but I do believe reading the response (even when ignoring it) is required when re-using a connection (which we don't do right now, but might do later).

**Comment by JordanP** [comment]
The HTTP connection pooling work "fixed" this issue/question.
