### ISSUE TITLE
DiskFileReader.zero_copy_send does not work if the sproxyd http front server doeas not keepalive connections

### ISSUE THREAD

**Issue by cazino** [scality/ScalitySproxydSwift#93]
When the http server standing in front of sproxyd does not keepalive its connections, the following backtraces can be observed when DiskFileReader.zero_copy_send is called.

/opt/stack/swift/swift/obj/server.py", line 764, in zero_copy_iter#012 app_iter.zero_copy_send(wsockfd)#12 File "/usr/lib/python2.6/site-packages/swift_scality_backend-0.3.2_139_g9debcd6-py2.6.egg/swift_scality_backend/utils.py", line 73, in wrapped#012 result = f(args, *kwargs)#12 File "/usr/lib/python2.6/site-packages/swift_scality_backend-0.3.2_139_g9debcd6-py2.6.egg/swift_scality_backend/diskfile.py", line 182, in zero_copy_send#012 resp.fileno(), wsockfd, length=to_splice)#12 File "/usr/lib/python2.6/site-packages/swift_scality_backend-0.3.2_139_g9debcd6-py2.6.egg/swift_scality_backend/http_utils.py", line 118, in fileno#012 return self.fp.fileno()#12 File "/usr/lib64/python2.6/socket.py", line 313, in fileno#012 return self._sock.fileno()#12 File "", line 1, in fileno#012 File "/usr/lib64/python2.6/socket.py", line 167, in _dummy#012 raise error(EBADF, 'Bad file descriptor')#012error: [Errno 9] Bad file descriptor (txn: tx1ccb1340406b41a7ad6c4-0055080e0d)

Basically the socket is closed by the httplib during the getresponse call, and zero_copy_send expects it to be opened even after that.

Some hints on the code path being used that leads to such a error : 
https://github.com/scality/ScalitySproxydSwift/blob/master/swift_scality_backend/diskfile.py#L157
https://hg.python.org/cpython/file/0f520ed901a5/Lib/httplib.py#l479
https://hg.python.org/cpython/file/0f520ed901a5/Lib/httplib.py#l1000
and finally : https://github.com/scality/ScalitySproxydSwift/blob/master/swift_scality_backend/diskfile.py#L180 wich expects the socket to be opened and raises the error.

I tried a patch where https://github.com/scality/ScalitySproxydSwift/blob/master/swift_scality_backend/diskfile.py#L180 is called only if 'to_splice' evaluates to true, and it does not seem to improve the situation.

This also is also related to #92.

**Comment by NicolasT** [comment]
I guess we could add a `close` method to `SomewhatBufferedHTTPConnection` which doesn't do anything at all, and have a `real_close` method in case we actually want to close a connection somewhere (even though that feels like an incredibly ugly hack).
